### ISSUE TITLE
I wanted to ask you Something

### ISSUE THREAD

**Issue by Sypher0Dronzer** [asad-bashi/BlogCity-Server#1]
Hi there, I came across your redit post link: https://www.reddit.com/r/node/comments/xw15iw/cors_issue_resolved_yet_cookie_is_still_not_being/

I am running into the same problem since I have frontend and backend hosted in different domains , also I have used passport js. 
You have made this project about 2 yrs ago, can you tell me if you figured out how to solve the error. 
I would be really grateful, I am  trying to find a solution for it for almost a month now

Thank you @asad-bashi

**Comment by asad-bashi** [comment]
Hi

I don’t remember exactly how I fixed it since it was a long time ago.
However I do know this post is what got me on the right track.


https://stackoverflow.com/questions/46288437/set-cookies-for-cross-origin-requests


Best of luck.

**Comment by Sypher0Dronzer** [comment]
Thank your for replying but , I still cant find the solution to my problem. Would you mind checking the repo for me if time permits?

**Comment by Sypher0Dronzer** [comment]
an update, i found the solution thank you brother!
